# Generated by Django 4.2.7 on 2023-12-22 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="datetime",
            new_name="dateTime",
        ),
    ]
