# Generated by Django 4.2.7 on 2023-12-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0002_rename_datetime_invoice_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='datetime',
            new_name='dateTime',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='invoice_id',
            new_name='invoiceId',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='appointment_id',
            new_name='appointmentId',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='services_ids',
            new_name='servicesIds',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='bill',
            name='paymentMethod',
            field=models.CharField(choices=[('ON', 'Card'), ('OF', 'Offline')], default='OF', max_length=2),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patientId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending Payment'), ('PD', 'Paid')], default='PN', max_length=2),
        ),
    ]
