# Generated by Django 4.2.7 on 2023-12-31 22:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing_app", "0004_alter_invoice_appointmentid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="amount",
        ),
        migrations.AddField(
            model_name="invoice",
            name="amountsAfterInsurance",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), default=0, size=None
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="servicesAmounts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), default=0, size=None
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="servicesNames",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), default=0, size=None
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="total",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoice",
            name="servicesIds",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), size=None
            ),
        ),
    ]
